# Generated by Django 4.0.4 on 2022-05-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_file_delete_blog_delete_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
